/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho;

import Modelo.Musicas;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ht3000222
 */
public final class ExMusicas extends javax.swing.JPanel {
        String nomeMusica;
        Reproducao r;
    public ExMusicas() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jtMusica.getModel();
        jtMusica.setRowSorter(new TableRowSorter(modelo));
        
        readJTable();
    }
    
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jtMusica.getModel();
        
        AcessoMusica accMus = new AcessoMusica();
        
        for(Musicas mus: accMus.read()){
            modelo.addRow(new Object[]{
                mus.getIdMusica(),
                mus.getNomeMusica(),
                mus.getIdCantor()
            });    

        }
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtMusica = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(350, 320));
        setMinimumSize(new java.awt.Dimension(350, 320));
        setPreferredSize(new java.awt.Dimension(350, 320));

        jtMusica.setBackground(new java.awt.Color(0, 0, 0));
        jtMusica.setForeground(new java.awt.Color(255, 255, 255));
        jtMusica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Música", "Cantor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtMusica.setGridColor(new java.awt.Color(0, 0, 0));
        jtMusica.setSelectionBackground(new java.awt.Color(204, 0, 0));
        jScrollPane1.setViewportView(jtMusica);
        if (jtMusica.getColumnModel().getColumnCount() > 0) {
            jtMusica.getColumnModel().getColumn(0).setMinWidth(55);
            jtMusica.getColumnModel().getColumn(0).setPreferredWidth(55);
            jtMusica.getColumnModel().getColumn(0).setMaxWidth(55);
            jtMusica.getColumnModel().getColumn(1).setMinWidth(200);
            jtMusica.getColumnModel().getColumn(1).setPreferredWidth(200);
            jtMusica.getColumnModel().getColumn(1).setMaxWidth(200);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtMusica;
    // End of variables declaration//GEN-END:variables




}
