/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho;

import Modelo.Musicas;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ht3000222
 */
public final class ExMusicas extends javax.swing.JPanel {
        String nomeMusica;
        Reproducao r;
    public ExMusicas() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jtMusica.getModel();
        jtMusica.setRowSorter(new TableRowSorter(modelo));
        
        readJTable();
    }
    
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jtMusica.getModel();
        
        AcessoMusica accMus = new AcessoMusica();
        
        for(Musicas mus: accMus.read()){
            modelo.addRow(new Object[]{
                mus.getIdMusica(),
                mus.getNomeMusica(),
                mus.getIdCantor()
            });    

        }
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtMusica = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(350, 320));
        setMinimumSize(new java.awt.Dimension(350, 320));
        setPreferredSize(new java.awt.Dimension(350, 320));

        jtMusica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Música", "Cantor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtMusica);
        if (jtMusica.getColumnModel().getColumnCount() > 0) {
            jtMusica.getColumnModel().getColumn(0).setMinWidth(55);
            jtMusica.getColumnModel().getColumn(0).setPreferredWidth(55);
            jtMusica.getColumnModel().getColumn(0).setMaxWidth(55);
            jtMusica.getColumnModel().getColumn(1).setMinWidth(200);
            jtMusica.getColumnModel().getColumn(1).setPreferredWidth(200);
            jtMusica.getColumnModel().getColumn(1).setMaxWidth(200);
        }

        jButton1.setText("a");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        nomeMusica = (String) jtMusica.getValueAt(jtMusica.getSelectedRow(), 1);
        
        System.out.println("Nome da musica: " + nomeMusica);
      
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtMusica;
    // End of variables declaration//GEN-END:variables




}
